# MuP configuration for width scaling experiments

# MuP settings
mup:
  use_mup: true
  
  # Coordinate checking
  coord_check_enabled: true
  coord_check_nsteps: 3
  coord_check_nseeds: 1
  coord_check_tolerance: 2.0
  
  # Base shapes
  base_shapes_file: "./outputs/base_shapes.pt"
  save_base_shapes: true
  
  # Learning rate scaling
  base_lr: 3e-4
  lr_scale_output: true
  lr_scale_embeddings: true
  
  # Weight decay scaling
  base_weight_decay: 0.1
  scale_weight_decay: true
  
  # Initialization
  scale_init: true
  init_std: 0.02
  
  # Advanced features
  spectral_monitoring: true
  higher_order_mup: false
  
  # Validation thresholds
  activation_tolerance: 5.0

# Scaling configuration
scaling:
  # Base model dimensions (reference)
  base_n_embd: 256
  base_n_layer: 6
  base_n_head: 4
  
  # Target model dimensions
  target_n_embd: 768
  target_n_layer: 12
  target_n_head: 12
  
  # Delta model for computing base shapes
  delta_n_embd: 512
  delta_n_layer: 8
  delta_n_head: 8
  
  # Width multipliers for experiments
  width_multipliers: [0.5, 1.0, 2.0, 4.0]
  
  # Fixed dimensions
  vocab_size: 50304
  block_size: 1024

# Validation settings
validation:
  # Coordinate checking
  coord_check_widths: [256, 512, 1024]
  coord_check_layers: 
    - "transformer.h.0.attn"
    - "transformer.h.0.mlp"
    - "transformer.h.6.attn"
    - "transformer.h.6.mlp"
    - "transformer.ln_f"
  
  # Scaling tests
  scaling_test_widths: [256, 512, 768, 1024]
  scaling_test_steps: 1000
  
  # Hyperparameter transfer
  transfer_base_width: 256
  transfer_target_widths: [512, 1024, 2048]
  transfer_steps: 5000
  
  # Spectral analysis
  spectral_layers:
    - "transformer.h.0"
    - "transformer.h.6" 
    - "transformer.h.11"
  spectral_frequency: 500
  spectral_top_k: 5
  
  # Tolerances
  coord_tolerance: 2.0
  activation_tolerance: 5.0
  spectral_tolerance: [0.1, 10.0]